24t16y/cfg/24t16y-modules.conf etc/modules-load.d
24t16y/cfg/config_db.json etc/sonic
24t16y/cfg/config_db_l2l3.json etc/sonic
24t16y/scripts/24t16y_platform.sh usr/bin
24t16y/scripts/24t16y_platform_routermac.py usr/bin
24t16y/modules/dal.ko /lib/modules/4.9.62/kernel/extra
24t16y/modules/centec_e550_24t16y_platform.ko /lib/modules/4.9.62/kernel/extra
24t16y/service/24t16y_platform.service /lib/systemd/system
