# linux kernel package for centec arm64



export KVERSION= 4.9.62
export LINUX_KERNEL_VERSION=4.9.62_4.9.62

$(LINUX_KERNEL)_SRC_PATH = $(PLATFORM_PATH)/linux
 
LINUX_KERNEL= linux-image-4.9.62-arm64.deb
SONIC_MAKE_DEBS += $(LINUX_KERNEL)

LINUX_KERNEL_DEBIMG = linux-image-4.9.62_4.9.62-1_arm64.deb
SONIC_MAKE_DEBS += $(LINUX_KERNEL_DEBIMG)

LINUX_KERNEL_HEADERS= linux-headers-4.9.62_4.9.62-1_arm64.deb
SONIC_MAKE_DEBS += $(LINUX_KERNEL_HEADERS)

