# centec platform configure

CENTEC_PLATFORM_CONF_VERSION = 1.0.0

CENTEC_PLATFORM_CONF = centec-platform-conf_$(CENTEC_PLATFORM_CONF_VERSION)_$(PLATFORM_ARCH).deb
$(CENTEC_PLATFORM_CONF)_SRC_PATH = $(PLATFORM_PATH)/platform-conf
SONIC_DPKG_DEBS += $(CENTEC_PLATFORM_CONF)

SONIC_STRETCH_DEBS += $(CENTEC_PLATFORM_CONF)
