# Centec SAI

export CENTEC_SAI_VERSION = 1.5.1-1.0
export CENTEC_SAI = libsai_$(CENTEC_SAI_VERSION)_$(PLATFORM_ARCH).deb

$(CENTEC_SAI)_SRC_PATH = $(PLATFORM_PATH)/sai
SONIC_MAKE_DEBS += $(CENTEC_SAI)
